name 'ci'
maintainer 'Puneet Sachdev'
maintainer_email 'puneet.sachdev@gmail.com'
license 'all_rights'
description 'Installs/Configures ci'
long_description 'Installs/Configures ci'
version '0.1.0'
depends 'apt'
depends 'jenkins'
